name: Adronite CI/CD Integration

on:
  push:
    branches: [ main ]

jobs:
  adronite-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Submit to Adronite
        run: |
          set -euo pipefail  # fail on error, undefined var, pipe failure
          RESPONSE=$(curl -s -X POST "https://k8s-default-nextjs-a5450415b6-115226263.us-west-2.elb.amazonaws.com/api/v1/project/add_github_revision/" \
            -k -H "Content-Type: application/json" \
            -H "Authorization: Api-Key ${{ secrets.ADRONITE_API_KEY_SANDBOX }}" \
            -d '{
              "project_id": "id_wznp22b95u5htd76",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}"
            }')
          
          if [ "$(echo "$RESPONSE" | jq -r '.status')" != "success" ]; then
            echo "Submission failed: $RESPONSE" >&2
            exit 1
          fi
